apiVersion: v1
kind: Namespace
metadata:
  name: ros2-system
  labels:
    name: ros2-system
    app.kubernetes.io/name: ros2
    app.kubernetes.io/component: system
---
apiVersion: v1
kind: Namespace
metadata:
  name: ros2-apps
  labels:
    name: ros2-apps
    app.kubernetes.io/name: ros2
    app.kubernetes.io/component: applications
