/* Generated automatically by the program `gencodes'
   from the machine description file `md'.  */

#ifndef GCC_INSN_CODES_H
#define GCC_INSN_CODES_H

enum insn_code {
  CODE_FOR_nothing = 0,
  CODE_FOR_bswapsi2 = 1,
  CODE_FOR_bswaphi2 = 2,
  CODE_FOR_addsf3 = 3,
  CODE_FOR_subsf3 = 4,
  CODE_FOR_mulsf3 = 5,
  CODE_FOR_divsf3 = 6,
  CODE_FOR_sqrtsf2 = 7,
  CODE_FOR_floatsisf2 = 8,
  CODE_FOR_fix_truncsfsi2 = 9,
  CODE_FOR_addsi3 = 10,
  CODE_FOR_adddi3 = 11,
  CODE_FOR_subsi3 = 12,
  CODE_FOR_iprefetch = 13,
  CODE_FOR_subdi3 = 14,
  CODE_FOR_mulsi3 = 15,
  CODE_FOR_mulsidi3 = 16,
  CODE_FOR_umulsidi3 = 17,
  CODE_FOR_usmulsidi3 = 18,
  CODE_FOR_divsi3_internal = 22,
  CODE_FOR_udivsi3 = 23,
  CODE_FOR_negsi2 = 24,
  CODE_FOR_negdi2 = 25,
  CODE_FOR_one_cmplsi2 = 26,
  CODE_FOR_andsi3 = 28,
  CODE_FOR_iorsi3 = 29,
  CODE_FOR_xorsi3 = 30,
  CODE_FOR_zero_extendhisi2 = 31,
  CODE_FOR_zero_extendqihi2 = 32,
  CODE_FOR_zero_extendqisi2 = 33,
  CODE_FOR_extendqisi2 = 34,
  CODE_FOR_extendhisi2 = 35,
  CODE_FOR_extendsidi2 = 36,
  CODE_FOR_movsi_status = 38,
  CODE_FOR_movsi4_rev = 44,
  CODE_FOR_ashlsi3_bshift = 48,
  CODE_FOR_seq_internal_pat = 63,
  CODE_FOR_sne_internal_pat = 64,
  CODE_FOR_cstoresf4 = 65,
  CODE_FOR_branch_zero = 66,
  CODE_FOR_branch_compare = 67,
  CODE_FOR_jump = 68,
  CODE_FOR_indirect_jump_internal1 = 69,
  CODE_FOR_tablejump_internal1 = 70,
  CODE_FOR_return_internal = 74,
  CODE_FOR_simple_return_internal = 75,
  CODE_FOR_blockage = 76,
  CODE_FOR_call_internal_plt = 77,
  CODE_FOR_call_internal1 = 78,
  CODE_FOR_call_value_intern_plt = 79,
  CODE_FOR_call_value_intern = 80,
  CODE_FOR_nop = 81,
  CODE_FOR_trap = 82,
  CODE_FOR_set_got = 83,
  CODE_FOR_set_text = 84,
  CODE_FOR_clzsi2 = 85,
  CODE_FOR_atomic_compare_and_swapsi = 86,
  CODE_FOR_divsi3 = 87,
  CODE_FOR_movdi = 88,
  CODE_FOR_movsi = 89,
  CODE_FOR_movhi = 90,
  CODE_FOR_movqi = 91,
  CODE_FOR_cpymemsi = 92,
  CODE_FOR_movsf = 93,
  CODE_FOR_movdf = 94,
  CODE_FOR_ashlsi3 = 95,
  CODE_FOR_ashrsi3 = 96,
  CODE_FOR_lshrsi3 = 97,
  CODE_FOR_cstoresi4 = 98,
  CODE_FOR_cbranchsi4 = 99,
  CODE_FOR_cbranchsi4_reg = 100,
  CODE_FOR_cbranchsf4 = 101,
  CODE_FOR_condjump = 102,
  CODE_FOR_indirect_jump = 103,
  CODE_FOR_tablejump = 104,
  CODE_FOR_tablejump_internal3 = 105,
  CODE_FOR_tablejump_internal4 = 106,
  CODE_FOR_prologue = 107,
  CODE_FOR_epilogue = 108,
  CODE_FOR_allocate_stack = 109,
  CODE_FOR_save_stack_block = 110,
  CODE_FOR_restore_stack_block = 111,
  CODE_FOR_return = 112,
  CODE_FOR_simple_return = 113,
  CODE_FOR_call = 114,
  CODE_FOR_call_internal0 = 115,
  CODE_FOR_call_internal_plt0 = 116,
  CODE_FOR_call_value = 117,
  CODE_FOR_call_value_internal = 118,
  CODE_FOR_call_value_intern_plt0 = 119,
  CODE_FOR_untyped_call = 120,
  CODE_FOR_eh_return = 121
};

const unsigned int NUM_INSN_CODES = 122;
#endif /* GCC_INSN_CODES_H */
