[workspace]
resolver = "2"
members = [
    "crates/wasmbed-k8s-controller",
    "crates/wasmbed-k8s-resource",
    "crates/wasmbed-protocol",
    "crates/wasmbed-types",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.88.0"
repository = "https://github.com/turlando/wasmed"
license = "AGPL-3.0"

[workspace.metadata.crane]
name = "wasmbed"

[workspace.lints.rust]
arithmetic_overflow = "deny"
unnecessary_transmutes = "deny"

[workspace.lints.clippy]
checked_conversions = "deny"
cast_possible_truncation = "deny"
cast_sign_loss = "deny"
cast_possible_wrap = "deny"
cast_precision_loss = "deny"
integer_division = "deny"
arithmetic_side_effects = "deny"
unchecked_duration_subtraction = "deny"
unwrap_used = "warn"
expect_used = "warn"
panicking_unwrap = "deny"
option_env_unwrap = "deny"
indexing_slicing = "deny"
join_absolute_paths = "deny"
serde_api_misuse = "deny"
uninit_vec = "deny"
transmute_ptr_to_ref = "deny"
transmute_undefined_repr = "deny"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
