apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-gateway
  namespace: wasmbed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-gateway
  template:
    metadata:
      labels:
        app: mock-gateway
    spec:
      containers:
      - name: mock-gateway
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: mock-gateway-service
  namespace: wasmbed
spec:
  selector:
    app: mock-gateway
  ports:
  - name: http
    port: 8080
    targetPort: 80
  type: ClusterIP
