apiVersion: wasmbed.github.io/v0
kind: Device
metadata:
  name: riscv-board-1
  namespace: wasmbed
spec:
  publicKey: "riscv-board-1-public-key-12345"
status:
  phase: "Enrolled"
  gateway: "gateway-1"
  connectedSince: "2025-09-27T17:00:00Z"
  lastHeartbeat: "2025-09-27T17:00:00Z"
  pairingMode: false
