apiVersion: v1
kind: ConfigMap
metadata:
  name: wasmbed-gateway-config
  namespace: wasmbed
data:
  gateway.yaml: |
    server:
      bind_addr: "0.0.0.0:8080"
      tls_bind_addr: "0.0.0.0:4423"
      max_connections: 1000
      connection_timeout: "30s"
      read_timeout: "10s"
      write_timeout: "10s"
    
    tls:
      enabled: true
      cert_file: "/etc/wasmbed-gateway/certs/tls.crt"
      key_file: "/etc/wasmbed-gateway/certs/tls.key"
      ca_file: "/etc/wasmbed-gateway/ca/ca-cert.pem"
      min_version: "1.2"
      cipher_suites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    
    logging:
      level: "info"
      format: "json"
      output: "stdout"
    
    metrics:
      enabled: true
      bind_addr: "0.0.0.0:9090"
      path: "/metrics"
    
    security:
      max_request_size: "10MB"
      rate_limit:
        enabled: true
        requests_per_minute: 1000
        burst: 100
    
    wasm:
      runtime_config:
        max_memory: "128MB"
        max_cpu_time: "100ms"
        max_instances: 100
        sandbox_mode: true
