apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.wasmbed.github.io
spec:
  group: wasmbed.github.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
                nullable: true
              wasmBytes:
                type: string
              targetDevices:
                type: object
                properties:
                  deviceNames:
                    type: array
                    items:
                      type: string
                    nullable: true
                  selectors:
                    type: object
                    nullable: true
                  allDevices:
                    type: boolean
                    nullable: true
              config:
                type: object
                nullable: true
              metadata:
                type: object
                nullable: true
            required: ["name", "wasmBytes", "targetDevices"]
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Creating", "Deploying", "Running", "PartiallyRunning", "Failed", "Stopping", "Stopped", "Deleting"]
              deviceStatuses:
                type: object
                nullable: true
              statistics:
                type: object
                nullable: true
              lastUpdated:
                type: string
                nullable: true
              error:
                type: string
                nullable: true
  scope: Namespaced
  names:
    plural: applications
    singular: application
    kind: Application
    shortNames:
    - app
