[package]
name = "test-tls-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "test-tls-utils"
path = "src/main.rs"

[dependencies]
wasmbed-tls-utils = { path = "../crates/wasmbed-tls-utils" }
