apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gateways.wasmbed.io
spec:
  group: wasmbed.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              endpoint:
                type: string
                description: "Gateway endpoint URL"
              port:
                type: integer
                default: 8080
              tlsPort:
                type: integer
                default: 8443
              region:
                type: string
              capabilities:
                type: array
                items:
                  type: string
              maxDevices:
                type: integer
                default: 100
              resources:
                type: object
                properties:
                  memory:
                    type: string
                  cpu:
                    type: string
                  storage:
                    type: string
              config:
                type: object
                properties:
                  enrollmentTimeout:
                    type: string
                    default: "5m"
                  heartbeatInterval:
                    type: string
                    default: "30s"
                  connectionTimeout:
                    type: string
                    default: "10m"
            required: ["endpoint"]
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Failed", "Stopped"]
              connectedDevices:
                type: integer
              enrolledDevices:
                type: integer
              lastHeartbeat:
                type: string
                format: date-time
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
              resources:
                type: object
                properties:
                  memory:
                    type: string
                  cpu:
                    type: string
                  storage:
                    type: string
  scope: Namespaced
  names:
    plural: gateways
    singular: gateway
    kind: Gateway
    shortNames:
    - gw
